---
name: Docker Build and Push

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/cabrinha/city-crawler
          tags: |
            type=ref,event=branch,prefix=backend-
            type=ref,event=pr,prefix=backend-
            type=semver,pattern={{version}},prefix=backend-
            type=semver,pattern={{major}}.{{minor}},prefix=backend-

      - name: Docker meta frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/cabrinha/city-crawler
          tags: |
            type=ref,event=branch,prefix=frontend-
            type=ref,event=pr,prefix=frontend-
            type=semver,pattern={{version}},prefix=frontend-
            type=semver,pattern={{major}}.{{minor}},prefix=frontend-

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max